### ISSUE TITLE
Edit a recurring event

### ISSUE THREAD

**Issue by PierreMasselot1** [ECSE-428-Group-5-W-2023/OnCampus#6]
## Todo
- [x] #38
- [x] #39
- [x] #40

**Comment by samperezh** [comment]
- [ ] Write the business method edit_recurring_event
- [ ] Set up PUT endpoint 
- [ ] Create the interface for editing a recurring event 
- [ ] Write unit tests 
- [ ] Write Gherkin tests
